[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "elf2uf2-rs -d"

[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]

linker = "flip-link"
rustflags = ["-C", "link-arg=-Tlink.x"]