[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "picotool load -u -v -x -t elf"

[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]

linker = "flip-link"
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=--verbose",
    "-C", "link-arg=-Tlink.x",
    "-C", "no-vectorize-loops",
    ]